name: instagram_clone
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^1.0.0-dev.11
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4
  expandable_bottom_sheet: ^1.1.1
  google_fonts: ^2.1.0
  enum_to_string: ^2.0.1
  intl: ^0.17.0
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.1.4
  freezed_annotation: ^0.15.0
  equatable: ^2.0.3
  firebase_storage: ^10.0.6
  timeago: ^3.1.0
  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed: ^0.15.0
  json_serializable: ^6.0.1
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/logos/facebook.jpg
    - assets/logos/google.jpg
    - assets/images/
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf